PWD = $(shell pwd)

.DEFAULT_GOAL = all                # should be unneccessary

binary_name = hello                 # desired bin name

include ../Makefile.pi                # compilation logic
# aditional project-specific flags
CFLAGS +=
